# Grayscale images
- จะเหลือเพียง 3 -> 1 byte (1 space) เพราะเอาทั้ง 3 มาต่อกันแบบ linear
- เรียกลำดับค่าสีจากน้อย -> มาก ```G -> R -> B```
- ลำดับการเรียงspace ``` B -> G -> R ```
- 3 ชั้นคือ 3ช่องสี Blue Green Red และแต่ละชั้นเก็บความเข้มสี 0-255

### โค้ดแสดงรูปภาพ ด้วยชั้นสเปซ B(0) -> G(1) -> R(2)

In [1]:
import cv2
import numpy as np

In [2]:
def show_image(img):
    cv2.imshow('Lena Image', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [3]:
img = cv2.imread('./week_introduction/lena.png')

In [4]:
show_image(img[:,:])#[:,:] show full image every row and column default is color image

In [6]:
#imread มี 2 args (path, flag(default=1))
# 1 = color, 0 = grayscale, -1 = unchanged

print(cv2.IMREAD_COLOR, "color")
print(cv2.IMREAD_GRAYSCALE, "grayscale")
print(cv2.IMREAD_UNCHANGED, "unchanged")

1 color
0 grayscale
-1 unchanged


จะได้ผลลัพท์การกรองแต่ละชั้น (img[:,:,0]) จะกรองชั้นที่มีสีของ B ผสมถ้ามีเป็นสีขาว=255 สีดำ=0 
สีเทา=128

### ส่วนอันนี้เป็นการต่อรูปทั้ง3ชั้นแบบแนวขวาง

In [7]:
#ปกติ img3.shape จะได้เป็น tuple
#แต่พอเขียนแบบนี่จะได้ int ธรรมดา
print(type(img), img.shape)
b, g, r = cv2.split(img) # split color image to 3 channel
print(type(b), b.shape)
print(type(g), g.shape)
print(type(r), r.shape)

<class 'numpy.ndarray'> (512, 512, 3)
<class 'numpy.ndarray'> (512, 512)
<class 'numpy.ndarray'> (512, 512)
<class 'numpy.ndarray'> (512, 512)


In [8]:
img2 = cv2.hconcat([b, g, r])  # concatenate 3 channel images side by side 
#row need to be same, column can be different

In [9]:
# vconcat = ต่อกันแนวตั้ง
img3 = cv2.vconcat([b, g, r])
show_image(img3)

In [10]:
show_image(img2)

### แสดงการรวมกันของ space

```0.1140*img[i, j, 0] + 0.5870*img[i, j, 1] + 0.2989*img[i, j, 2]```

**ค่าสัมประสิทพวกนี้คือ** -> มาตรฐานสากลของการแปลงภาพสีไปเป็น Grayscale ที่เรียกว่า:

📌 ITU-R BT.601 (หรือ Rec.601)

ใช้ในระบบวิดีโอและภาพดิจิทัลมานาน เช่น SDTV
สูตรเดิมสำหรับแปลง RGB → Luminance (ความสว่าง)

gray = 0.1140 B + 0.5870 G + 0.2989 R

จะเห็นว่า Green มีค่ามากสุดแปลว่า -> **ความเข้มน้อย** เพราะตาคนเรารับสีเขียวได้ดีกว่าแดง, น้ำเงิน

In [11]:
img = cv2.imread('./week_introduction/lena.png', cv2.IMREAD_COLOR) 
row,col, n =img.shape
print(row, col, n)

512 512 3


In [12]:
gray = np.zeros([row, col], dtype='float')# สร้าง array 10x10 ที่มีค่าเป็น 0 และ type เป็น float
print(gray)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### ทำไมต้องแปลงเป็น float16 ก่อน แล้วค่อยแปลงกลับเพื่อดูผลลัพธ์ ?

เพราะรูปที่ได้จาก cv จะเป็น int แต่เราจะทำ garyscale ซึ่งต้องคูณค่าสัมประสิทที่เป็นทศนิยม

จึงต้องแปลงเป็น float16 -> ทำ garyscale -> แปลงเป็น int เพื่อดูผลลัพธ์

In [13]:
img = img.astype(np.float16) #แปลง type ของ img เป็น float16 ก่อนที่จะ process รูป
for i in range(row):
    for j in range(col):
        gray[i, j] = 0.1140*img[i, j, 0] + 0.5870*img[i, j, 1] + 0.2989*img[i, j, 2]

In [14]:
gray = gray.astype(np.uint8) # แปลง type ของ gray กลับเป็น uint8เพื่อให้แสดงผลได้ถูกต้อง

In [15]:
show_image(gray)

### อธิบายโค้ด Python : Loop

In [16]:
#x = range(10) #วน loop 0-9
#x = range(1, 10) #วน loop 1-9
x = range(1, 10, 2) #วน loop 1-9 step 2

print("len: ",len(x))

# x คือ collective data
for i in x:
    print(i)

len:  5
1
3
5
7
9


### Data Collections
- List: เป็นลำดับของข้อมูลที่สั่งได้ (ordered) และเปลี่ยนแปลงได้ (mutable)
- Tuple: เป็นลำดับของข้อมูลที่สั่งได้ (ordered) แต่เปลี่ยนแปลงไม่ได้ (immutable)
- Set: เป็นชุดข้อมูลที่ไม่เรียงลำดับ (unordered) และไม่มีข้อมูลซ้ำกัน (unique)
- Dictionary (dict): เป็นชุดข้อมูลแบบคีย์-ค่า (key-value) ที่ไม่เรียงลำดับ (unordered) และไม่มีคีย์ซ้ำกัน 

#### Example

In [1]:
#List
x = ["apple", "banana", "cherry"]
print(type(x))

<class 'list'>


In [2]:
#Tuple
y = ("apple", "banana", "cherry")
print(type(y))

<class 'tuple'>


In [3]:
#Set
z = {"apple", "banana", "cherry"}
print(type(z))

<class 'set'>


In [4]:
#Dictionary
mydict = {
    "name": "John",
    "age": 30,
    "city": "New York"
}
print(type(mydict))

<class 'dict'>
